# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2

php_cs_fixer: &php_cs_fixer
  run: |
    scripts/php_cs_fixer.sh
    #composer run php-cs-fixer-dry-run || (echo "Coding standards are not respected. Run 'composer run php-cs-fixer'" && exit 1)

jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:5.6-cli-stretch

    steps:
      - checkout
      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - <<: *php_cs_fixer
