# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2

references:
  commands:
    php_cs_fixer: &php_cs_fixer
      command: |
        scripts/php_cs_fixer.sh
    install_compoer: &install_compoer
      name: composer install by composer-php-cs-fixer.json
      command: |
        composer install -n --prefer-dist

  restore_cache:
    restore_cache_composer_json: &restore_cache_composer_json
      keys:
        - v1-dependencies-{{ checksum "composer-php-cs-fixer.json" }}
        - v1-dependencies-

  saves_caches:
    save_cache_composer_json: &save_cache_composer_json
      key: v1-dependencies-{{ checksum "composer-php-cs-fixer.json" }}
      paths:
        - ./vendor

defaults: &defaults
  environment: COMPOSER composer-php-cs-fixer.json

jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/php:5.6-cli-stretch

    steps:
      - checkout
      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip
      - restore_cache: *restore_cache_composer_json
      - run: *install_compoer
      - save_cache: *save_cache_composer_json
      - <<: *php_cs_fixer

